config/routes.rb
Rails.application.routes.draw do
  resources :labs
  
  get 'home/index'


  root 'home#index'

end

app/models/lab.rb
class Lab < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/labs_controller.rb
class LabsController < ApplicationController

	def index
		@labs = Lab.all
	end

	def show
    	@lab = Lab.find(params[:id])
  	end

	def create
		@lab = Lab.new(lab_params)
		if @lab.save 
			redirect_to @lab
		else 
			render 'new'
		end
	end

	private
	
	def lab_params
		params.require(:lab).permit(:name, :address, :logo)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/labs_helper.rb
module LabsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/labs/index.html.erb
<h1>Listing labs</h1>
 <%= link_to 'New Lab', new_lab_path %>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Logo</th>
  </tr>
 
  <% @labs.each do |lab| %>
    <tr>
      <td><%= lab.name %></td>
      <td><%= lab.address %></td>
      <td><%= lab.logo %></td>
    </tr>
  <% end %>
</table>

app/views/labs/new.html.erb
<%= form_for :lab, url: labs_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </p>
 
  <p>
    <%= f.label :logo %><br>
    <%= f.text_field :logo %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', labs_path %>

app/views/labs/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @lab.name %>
</p>
 
<p>
  <strong>Address:</strong>
  <%= @lab.address %>
</p>

<p>
  <strong>Logo:</strong>
  <%= @lab.logo %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Labco</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>